In [58]:
import pandas as pd
import numpy as np
import plotly
import plotly.plotly as py
import plotly.graph_objs as go

In [60]:
lite_df = pd.read_csv('/Users/newuser/Dropbox/Datamining/Crypto-Pirates/Datasets/litecoin_price.csv',parse_dates=True,index_col=0)
lite_df['Close'].plot()

ModuleNotFoundError: No module named 'matplotlib'

In [45]:
lite

             Open   High    Low  Close         Volume     Market Cap
Date
2017-10-03  53.39  53.59  51.59  52.35     88,516,100  2,840,540,000
2017-10-02  54.55  54.78  53.26  53.38     95,474,600  2,901,270,000
2017-10-01  55.14  55.16  53.63  54.54    100,183,000  2,931,740,000
2017-09-30  52.63  55.23  52.62  55.14    131,446,000  2,797,460,000
2017-09-29  54.11  54.16  50.42  52.62    186,560,000  2,875,460,000
2017-09-28  56.21  56.67  53.41  54.09    202,009,000  2,986,370,000
2017-09-27  51.58  56.54  51.58  56.28    220,363,000  2,739,380,000
2017-09-26  51.69  53.70  51.08  51.55    173,663,000  2,744,540,000
2017-09-25  47.62  52.44  47.57  51.58    208,641,000  2,527,830,000
2017-09-24  49.25  49.27  47.52  47.62     82,147,100  2,613,620,000
2017-09-23  48.16  49.79  46.69  49.27    142,073,000  2,554,900,000
2017-09-22  46.65  49.09  45.19  48.09    218,134,000  2,474,380,000
2017-09-21  51.66  52.31  45.67  46.61    229,363,000  2,739,370,000
2017-09-20  52.74  53.83  51.25  51.73    160,252,000  2,795,880,000
2017-09-19  55.68  55.88  51.05  52.84    286,583,000  2,950,880,000
2017-09-18  48.53  55.61  48.53  55.53    408,675,000  2,571,070,000
2017-09-17  48.23  49.88  45.12  48.49    245,262,000  2,554,450,000
2017-09-16  48.13  52.83  46.46  48.26    562,278,000  2,548,580,000
2017-09-15  41.69  50.65  32.03  48.21  1,554,340,000  2,206,520,000
2017-09-14  61.64  62.43  41.25  41.58    749,714,000  3,261,960,000
2017-09-13  64.32  64.60  58.93  61.73    501,522,000  3,402,820,000
2017-09-12  66.24  70.25  63.86  64.23    481,218,000  3,503,300,000
2017-09-11  61.65  67.23  61.37  66.04    412,076,000  3,259,510,000
2017-09-10  65.80  65.95  57.06  61.61    529,848,000  3,478,400,000
2017-09-09  67.21  69.55  64.01  66.01    467,895,000  3,551,950,000
2017-09-08  78.45  80.13  63.83  67.79    930,673,000  4,144,630,000
2017-09-07  79.88  81.06  75.59  78.48    526,829,000  4,218,690,000
2017-09-06  71.78  80.64  71.51  80.11    830,718,000  3,789,670,000
2017-09-05  65.25  72.44  59.05  71.29  1,016,090,000  3,444,150,000
2017-09-04  76.73  76.73  61.24  65.21    922,041,000  4,049,140,000
...           ...    ...    ...    ...            ...            ...
2013-05-27   3.23   3.26   3.02   3.10              -     58,130,800
2013-05-26   3.12   3.33   3.09   3.25              -     56,123,900
2013-05-25   3.19   3.20   3.05   3.12              -     57,165,800
2013-05-24   3.17   3.19   3.04   3.18              -     56,747,200
2013-05-23   3.12   3.19   3.09   3.18              -     55,727,000
2013-05-22   3.09   3.14   3.03   3.12              -     55,165,300
2013-05-21   3.19   3.22   3.04   3.09              -     56,887,600
2013-05-20   3.31   3.32   3.15   3.18              -     58,962,900
2013-05-19   3.30   3.41   3.19   3.30              -     58,645,400
2013-05-18   3.20   3.36   3.13   3.29              -     56,721,100
2013-05-17   2.89   3.34   2.87   3.19              -     51,195,900
2013-05-16   2.93   2.97   2.69   2.92              -     51,790,900
2013-05-15   2.82   3.04   2.64   2.94              -     49,842,500
2013-05-14   3.28   3.33   2.78   2.82              -     57,812,000
2013-05-13   3.26   3.37   3.20   3.28              -     57,363,200
2013-05-12   3.36   3.42   3.22   3.27              -     59,052,900
2013-05-11   3.46   3.48   3.30   3.35              -     60,658,000
2013-05-10   3.41   3.63   3.37   3.44              -     59,588,000
2013-05-09   3.40   3.44   3.29   3.42              -     59,337,100
2013-05-08   3.28   3.49   3.28   3.41              -     57,196,300
2013-05-07   3.37   3.41   2.94   3.33              -     58,588,300
2013-05-06   3.59   3.78   3.12   3.37              -     62,356,000
2013-05-05   3.49   3.69   3.35   3.59              -     60,525,000
2013-05-04   3.03   3.64   2.90   3.48              -     52,476,400
2013-05-03   3.39   3.45   2.40   3.04              -     58,607,400
2013-05-02   3.78   4.04   3.01   3.37              -     65,242,700
2013-05-01   4.29   4.36   3.52   3.80              -     73,901,200
2013-04-30   4.40   4.57   4.17   4.30              -     75,726,800
2013-04-29   4.37   4.57   4.23   4.38              -     74,952,700
2013-04-28   4.30   4.40   4.18   4.35              -     73,773,400

[1620 rows x 6 columns]

In [46]:
lite_df['Close'].mean()

9.3301234567901226

In [47]:
dataset = lite_df['Close']

In [48]:
dataset

0       52.35
1       53.38
2       54.54
3       55.14
4       52.62
5       54.09
6       56.28
7       51.55
8       51.58
9       47.62
10      49.27
11      48.09
12      46.61
13      51.73
14      52.84
15      55.53
16      48.49
17      48.26
18      48.21
19      41.58
20      61.73
21      64.23
22      66.04
23      61.61
24      66.01
25      67.79
26      78.48
27      80.11
28      71.29
29      65.21
        ...
1590     3.10
1591     3.25
1592     3.12
1593     3.18
1594     3.18
1595     3.12
1596     3.09
1597     3.18
1598     3.30
1599     3.29
1600     3.19
1601     2.92
1602     2.94
1603     2.82
1604     3.28
1605     3.27
1606     3.35
1607     3.44
1608     3.42
1609     3.41
1610     3.33
1611     3.37
1612     3.59
1613     3.48
1614     3.04
1615     3.37
1616     3.80
1617     4.30
1618     4.38
1619     4.35
Name: Close, Length: 1620, dtype: float64